hosts:
  - db01.example.ru
  - db02.example.ru
  - example.ru
  - app01.example.ru
  - app02.example.ru

groups:
  - name: web
    hosts:
      - example.ru
    triggers:
      - process
      - java
  - name: db
    hosts:
      - db01.example.ru
      - db02.example.ru
    triggers:
      - oracle
  - name: app
    hosts:
      - app01.example.ru
      - app02.example.ru
    triggers:
      - java
  - name: all-linux
    hosts: 
      - app01.example.ru
    checks:
      - http-process
    triggers:
      - disk


checks:
  - name: http-process
    period: '* * * * *'
    type: httpByStatus
    url: http://localhost/ok
  - name: base-check
    period: '* * * * *'
    command: uptime
    type: shell
  - name: disk-root
    period: '* * * * *'
    command: uptime
    type: shell
  - name: process-java
    period: '* * * * *'
    command: uptime
    type: shell


triggers: 
  - name: process
    check: http-process
    description: Проверка процессинга по админке
    result: code equal 500
  - name: oracle
    check: base-check
    description: Проверка базы
    result: return equal 1
  - name: java
    check: process-java
    description: Проверяем что java работает
    result: return equal 1
  - name: disk
    check: disk-root
    description: Проверка свободного места
    result: free more 1000000 and used less 100
