hosts:
  - salt
groups:
  - name: salt
    hosts:
      - salt
    triggers:
      - networkt
    checks:
      - network

checks:
  - name: network
    period: '* * * * *'
    version: 3
    sequrityName: aes
    privType: AES
    privAuth: AuthPriv
    authType: SHA
    authPass: helloallhello
    privPass: helloallhello
    type: network.interface

triggers:
  - name: networkt
    checks:
      - network
    description: тупо проверка имени
    result: eth0:network.interface.name = "eth0" 



