hosts:
  - localhost

groups:
  - name: local
    hosts:
      - localhost
    triggers:
      - hostname
    checks:
      - uptime
      - boottime
      - loadaverage
      - intr
      - cpuinfo
      - switches
      - util
      - localtime
      - checkUbank

checks:
  - name: gethost
    period: '* * * * *'
    type: system.hostname
  - name: uptime
    period: '* * * * *'
    type: system.uptime
  - name: boottime
    period: '*/2 * * * *'
    type: system.boottime
  - name: loadaverage
    period: '* * * * *'
    type: system.cpu.loadavg
  - name: intr
    period: '* * * * *'
    type: system.cpu.intr
  - name: cpuinfo
    period: '* * * * *'
    type: system.cpu.info
  - name: switches
    period: '* * * * *'
    type: system.cpu.switches
  - name: util
    period: '* * * * *'
    type: system.cpu.util
  - name: localtime
    period: '* * * * *'
    type: system.localtime
  - name: checkUbank
    period: '* * * * *'
    type: http.simple
    url: http://ubank.ru
    redirects: 2

triggers:
  - name: hostname
    checks:
      - gethost
    description: тупо проверка имени
    result: system.hostname = "limbo-air"
