system:
  snmp:
    version: 3
    sequrityName: aes
    privType: AES
    privAuth: AuthPriv
    authType: SHA
    authPass: helloallhello
    privPass: helloallhello
  database:
    user: fixmon
    password: fixmon
    database: fixmon
    host: localhost
    port: 8086

hosts:
  - salt
  - yandex.ru

groups:
  - name: salt
    hosts:
      - salt
    triggers:
      - disk
    checks:
      - disk
  - name: external
    hosts:
      - yandex.ru
    triggers:
      - yandex



checks:
  - name: network
    period: '* * * * *'
    snmp:
      version: 3
      sequrityName: aes
      privType: AES
      privAuth: AuthPriv
      authType: SHA
      authPass: helloallhello
      privPass: helloallhello
    type: network.interface
  - name: disk
    period: '* * * * *'
    type: system.disk
    alias.root: '/'
    alias.swap: 'Swap space'
    alias.virtual: 'Virtual memory'
  - name: ya
    period: '* * * * *'
    type: http.simple
    url: http://yandex.ru
    redirects: 3
  - name: rambler
    period: '* * * * *'
    type: http.simple
    url: http://rambler.ru
    redirects: 3


triggers:
  - name: disk
    checks:
      - disk
    description: dist size here
    result: root:system.disk.free > 35GB && root:system.disk.used > 10GB && swap:system.disk.used > 1GB
  - name: networkt
    checks:
      - network
      - disk
    description: тупо проверка имени
    result: eth0:network.interface.name = "eth0" || lo:network.interface.name = "lo" || root:system.disk.free > 35GB
  - name: other
    checks:
      - network
    description: last here
    result: last(br0:network.interface.name,2) = "eth0"
  - name: yandex
    checks: 
      - ya
      - rambler
    description: yandex status
    result: ya:http.simple.status = 200 && rambler:http.simple.status = 200





