system:
  database:
    user: fixmon
    password: fixmon
    database: fixmon
    host: fixmon
    port: 8086

hosts:
  - salt
  - yandex.ru

groups:
  - name: salt
    hosts:
      - salt
    triggers:
      - disk
    checks:
      - disk
      - network
  - name: external
    hosts:
      - yandex.ru
    triggers:
      - yandex
      - rambler

checks:
  - name: network
    period: '* * * * *'
    type: network.interface
  - name: disk
    period: '* * * * *'
    type: system.disk
  - name: ya
    period: '* * * * *'
    type: http.simple
    url: http://yandex.rua
    redirects: 3
  - name: rambler
    period: '* * * * *'
    type: http.simple
    url: http://rambler.ru
    redirects: 3


triggers:
  - name: disk
    checks:
      - disk
    description: dist size here
    result: root:system.disk.free > 35GB 
  - name: networkt
    checks:
      - network
      - disk
    description: тупо проверка имени
    result: eth0:network.interface.name = "eth0" || lo:network.interface.name = "lo" || root:system.disk.free > 35GB
  - name: other
    checks:
      - network
    description: last here
    result: last(br0:network.interface.name,2) = "eth0"
  - name: yandex
    checks: 
      - ya
      - rambler
    description: yandex status
    result: ya:http.simple.status = 200 && rambler:http.simple.status = 200
  - name: rambler
    checks:
      - rambler
    description: rambler status
    result: rambler:http.simple.status = 300

