hosts:
  - db01.example.ru
  - db02.example.ru
  - example.ru
  - app01.example.ru
  - app02.example.ru
  - localhost
  - limbo-air

groups:
  - name: web
    hosts:
      - example.ru
    triggers:
      - process
      - java
  - name: db
    hosts:
      - db01.example.ru
      - db02.example.ru
    triggers:
      - oracle
  - name: app
    hosts:
      - app01.example.ru
      - app02.example.ru
    triggers:
      - java
  - name: all-linux
    hosts: 
      - app01.example.ru
    checks:
      - http-process
    triggers:
      - disk
  - name: local
    hosts: 
      - localhost
    triggers:
      - hostname
    checks:
      - http-process

checks:
  - name: gethost
    period: '* * * * *'
    type: system.hostname
  - name: http-process
    period: '* * * * *'
    type: http.simple
    url: http://ya.ru
    redirects: 4
  - name: base-check
    period: '* * * * *'
    command: uptime
    type: system.uptime
  - name: disk-root
    period: '* * * * *'
    command: uptime
    type: system.hostname
  - name: disk-usr
    period: '* * * * *'
    command: uptime
    type: system.hostname
  - name: disk-home
    period: '* * * * *'
    command: uptime
    type: system.hostname
  - name: process-java
    period: '* * * * *'
    command: uptime
    type: system.hostname


triggers: 
  - name: hostname
    checks: 
      - gethost
    description: тупо проверка имени
    result: system.hostname equal limbo-air 
  - name: process
    check: http-process
    description: Проверка процессинга по админке
    result: status equal 5
  - name: oracle
    check: base-check
    description: Проверка базы
    result: return equal 1
  - name: java
    check: process-java
    description: Проверяем что java работает
    result: return equal 1
  - name: disk
    checks:
      - disk-root
      - disk-usr
      - disk-home
    description: Проверка свободного места
    result: disk-home.free more 1000000 and disk-root.used less 100

