system:
  snmp:
    version: 3
    sequrityName: aes
    privType: AES
    privAuth: AuthPriv
    authType: SHA
    authPass: helloallhello
    privPass: helloallhello
  database:
    user: fixmon
    password: fixmon
    database: fixmon
    host: localhost
    port: 8086

hosts:
  - salt

groups:
  - name: salt
    hosts:
      - salt
    triggers:
      - disk
      - networkt
    checks:
      - network
      - disk

checks:
  - name: network
    period: '* * * * *'
    snmp:
      version: 3
      sequrityName: aes
      privType: AES
      privAuth: AuthPriv
      authType: SHA
      authPass: helloallhello
      privPass: helloallhello
    type: network.interface
  - name: disk
    period: '* * * * *'
    type: system.disk
    alias.root: '/'
    alias.swap: 'Swap space'
    alias.virtual: 'Virtual memory'

triggers:
  - name: disk
    checks:
      - disk
    description: dist size here
    result: root:system.disk.free > 35GB
  - name: networkt
    checks:
      - network
    description: тупо проверка имени
    result: eth0:network.interface.name = "eth0" 
  - name: other
    checks:
      - network
    description: last here
    result: last(br0:network.interface.name,2) = "eth0"




