hosts:
  - db01.example.ru
  - db02.example.ru
  - example.ru
  - app01.example.ru
  - app02.example.ru

groups:
  - name: web
    hosts:
      - example.ru
    triggers:
      - process
  - name: db
    hosts:
      - db01.example.ru
      - db02.example.ru
    triggers:
      - oracle
  - name: app
    hosts:
      - app01.example.ru
      - app02.example.ru
    triggers:
      - java
  - name: all-linux
    hosts: 
      - *
    triggers:
      - disk-root

triggers: 
  - name: process
    period: * * * * *
    check: http-process
    description: Проверка процессинга по админке
    result: code not eq 500
  - name: oracle
    period: * * * * *
    check: base-check
    description: Проверка базы
    result: return eq 1
  - name: java
    period: * * * * *
    check: process-java
    description: Проверяем что java работает
    result: return eq 1
  - name: disk
    period: * * * * *
    check: disk-root
    description: Проверка свободного места
    result: free gt 1000000

checks:
  - name: http-process
    type: httpByStatus
    url: http://localhost/ok
  - name: base-check
    command: uptime
    type: shell
  - name: disk-root
    command: uptime
    type: shell
  - name: process-java
    command: uptime
    type: shell

